In [1]:
import numpy as np
import copy

In [1]:
"""1  数值计算
2  数值索引
3  复数计算
4  函数运算
5  逻辑判断
6  类型转化
7  数组生成
8  结构变化
9  结构识别
10  代码申明
11  未知"""

'1  数值计算\n2  数值索引\n3  复数计算\n4  函数运算\n5  逻辑判断\n6  类型转化\n7  数组生成\n8  结构变化\n9  结构识别\n10  代码申明\n11  未知'

In [2]:
# packbits 字节压缩算法，具体见官方说明
# 结构变化 数值计算
a = np.array([[[1,0,1],
               [0,1,0]],
              [[1,1,0],
               [0,0,1]]])
b = np.packbits(a, axis=-1)
b

array([[[160],
        [ 64]],

       [[192],
        [ 32]]], dtype=uint8)

In [3]:
# pad 填充用，具体见官方案例
# 数组生成
a = [1, 2, 3, 4, 5]
print(np.pad(a, (2, 3), 'reflect'))
print(np.pad(a, (2, 3), 'reflect', reflect_type='odd'))
print(np.pad(a, (2, 3), 'symmetric'))
print(np.pad(a, (2, 3), 'symmetric', reflect_type='odd'))
print(np.pad(a, (2, 3), 'wrap'))

[3 2 1 2 3 4 5 4 3 2]
[-1  0  1  2  3  4  5  6  7  8]
[2 1 1 2 3 4 5 5 4 3]
[0 1 1 2 3 4 5 5 6 7]
[4 5 1 2 3 4 5 1 2 3]


In [4]:
# partition 根据已知顺序，按照给定的kth排序
# partition(a, kth, axis=-1, kind='introselect', order=None)
# 逻辑判断 数组生成
a = np.array([3, 4, 2, 1,5,10,-5])
print(np.partition(a, 3)) 
print(np.partition(a, (1, 5)))

[-5  1  2  3  4 10  5]
[-5  1  2  3  4  5 10]


In [5]:
# percentile 求取给定数组的百分位数，亦可是中位数（50/100）,可以沿轴。
# percentile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)
# 数值计算
a = np.array([[10, 7, 4], [3, 2, 1]])
print(np.percentile(a, 50)) # (3+4)/2 =3.5
m = np.percentile(a, 50, axis=0)
print(np.percentile(a, 50, axis=0)) # 0轴上取中位数
print(np.percentile(a, 50, axis=1, keepdims=False))
print(np.percentile(a, 50, axis=1, keepdims=True))

3.5
[6.5 4.5 2.5]
[7. 2.]
[[7.]
 [2.]]


In [6]:
# pi 获得圆周率
# 数值获取
np.pi

3.141592653589793

In [7]:
# piecewise 多条件的运算，满足条件则按规则转化
# 数组生成
y = np.linspace(-2.5, 2.5, 6)
print(np.piecewise(y, [y < 0, y >= 0], [lambda x: -x, lambda x: x]))
print(np.piecewise(y, [y < 0, y >= 0], [-1, 1]))

[2.5 1.5 0.5 0.5 1.5 2.5]
[-1. -1. -1.  1.  1.  1.]


In [8]:
# pkgload 父包什么的，不明所以
# 未知

In [9]:
# place 将select打包，等于是直接选择符合条件的数据进行运算。
# 数组生成 函数运算
arr = np.arange(6).reshape(2, 3)
np.place(arr, arr>2, [44, 55])
arr

array([[ 0,  1,  2],
       [44, 55, 44]])

In [10]:
# pmt 金融计算，计算贷款本金加利息的偿还额

In [11]:
# poly 得到以给定元组为根，以最高次项的常数系数为1的多项式
# 函数运算 数值计算
print(np.poly((0, 0, 0)))
print(np.poly((-1./2, 0, 1./2)))

[1. 0. 0. 0.]
[ 1.    0.   -0.25  0.  ]


In [12]:
# poly1d 构建一维多项式的方法，同时该对象可以接受多项式的运算
# 函数运算 数值计算
p = np.poly1d([1, 2, 3])
print(p)
p = np.poly1d([1,2,3], variable='z')
print(p)
p = np.poly1d([1, 2, 3], True) # (x-1)(x-2)(x-3) = x^3 - 6x^2 + 11x -6
print(p)

   2
1 x + 2 x + 3
   2
1 z + 2 z + 3
   3     2
1 x - 6 x + 11 x - 6


In [13]:
# polyadd 多项式相加
# 函数运算 数值计算
p1 = np.poly1d([1, 2])
p2 = np.poly1d([9, 5, 4])
print(p1)
print(p2)
print(np.polyadd(p1, p2))

 
1 x + 2
   2
9 x + 5 x + 4
   2
9 x + 6 x + 6


In [14]:
# polyder 多项式指定阶的导数的值
# 函数运算 数值计算
p = np.poly1d([1,1,1,1]) # y = x^3 + x^2 + x^1 + 1
print(p)
p2 = np.polyder(p) # y = 3x^2 + 2x + 1
p2(2.) # 3*2^2 + 2*2 + 1 = 17

   3     2
1 x + 1 x + 1 x + 1


17.0

In [15]:
# polydiv 多项式除法
# 函数运算 数值计算
x = np.array([3.0, 5.0, 2.0])
y = np.array([2.0, 1.0])#(3x^2 + 5x + 2)/(2x + 1) = 1.5x + 1.75 , 余0.25
np.polydiv(x, y)

(array([1.5 , 1.75]), array([0.25]))

In [16]:
# polyfit 根据点，拟合多项式曲线
# 函数运算 数值计算
x = np.array([0.0, 1.0, 2.0, 3.0,  4.0,  5.0])
y = np.array([0.0, 0.8, 0.9, 0.1, -0.8, -1.0])
z = np.polyfit(x, y, 3) # 根据已知点拟合一元三次方曲线
print(z)

[ 0.08703704 -0.81349206  1.69312169 -0.03968254]


In [2]:
# polyint 与多项式不定积分有关
# 函数运算 数值计算
p = np.poly1d([1,1,1])
P = np.polyint(p)
P = np.polyint(p, 3)
P

poly1d([0.01666667, 0.04166667, 0.16666667, 0.        , 0.        ,
       0.        ])

In [19]:
# polymul 一元多项式相乘
# 函数运算 数值计算
np.polymul([1, 2, 3], [9, 5, 1])  # (x^2+2x+3)*(9x^2+5x+1) == 9x4 + 23x3 + 38x2 + 17x1 + 3

array([ 9, 23, 38, 17,  3])

In [20]:
# np.polynomial不知道干啥用的
# 未知

In [21]:
# polysub 多项式的系数相减，获得新的多项式的系数
# 函数运算 数值计算
np.polysub([2, 10, -2], [3, 10, -4]) #(2 x^2 + 10 x - 2) - (3 x^2 + 10 x -4) = (-x^2 + 2)

array([-1,  0,  2])

In [22]:
# polyval ``p[0]*x**(N-1) + p[1]*x**(N-2) + ... + p[N-2]*x + p[N-1]`` 求多项式的y值
# 函数运算 数值计算
print(np.polyval([3,0,1], 5))  # 3 * 5**2 + 0 * 5**1 + 1
print(np.polyval(np.poly1d([3,0,1]), np.poly1d(5)))

76
 
76


In [3]:
# numpy.positive ##Returned array or scalar: y = +x. This is a scalar if x is a scalar.为啥没按描述给我结果
# 未知
np.positive([10,-1,2])

array([10, -1,  2])

In [24]:
# power幂指数计算
#  数值计算
x1 = range(6)
print(np.power(x1, 3))
x2 = [1.0, 2.0, 3.0, 3.0, 2.0, 1.0]
print(np.power(x1, x2))
x2 = np.array([[1, 2, 3, 3, 2, 1], [1, 2, 3, 3, 2, 1]])
print(np.power(x1, x2))

[  0   1   8  27  64 125]
[ 0.  1.  8. 27. 16.  5.]
[[ 0  1  8 27 16  5]
 [ 0  1  8 27 16  5]]


In [25]:
# ppmt 根据贷款本金计算付款
# 见rate，pv等

In [26]:
# print_function 打印属性
np.print_function

_Feature((2, 6, 0, 'alpha', 2), (3, 0, 0, 'alpha', 0), 65536)

In [27]:
# printoptions 打印的格式的更改
with np.printoptions(precision=2):
    print((np.array([2.0])) / 3)

[0.67]


In [28]:
# product == prod 给定数组的所有元素乘积，或者按行按列的数组乘积
# 数值计算
print(np.prod([]))
print(np.prod([1.,2.]))
print(np.prod([[1.,2.],[3.,4.]]))
print(np.prod([[1.,2.],[3.,4.]], axis=1))
print(np.prod([1, 2], initial=5))

1.0
2.0
24.0
[ 2. 12.]
10


In [29]:
# promote_types 对数据格式做处理，返回最小维度数据类型
np.promote_types('f4', 'f8')

dtype('float64')

In [30]:
# ptp 沿轴获取最大最小值
# 数值计算
x = np.arange(4).reshape((2,2))
print(x)
print(np.ptp(x, axis=0))
print(np.ptp(x, axis=1))

[[0 1]
 [2 3]]
[2 2]
[1 1]


In [31]:
# put 一维数组根据索引更改值,用v的值替换数组a中的ind（索引）的值。
# Mode可以为raise/wrap/clip。Clip：如果给定的ind超过了数组的大小，那么替换最后一个元素。
# 数组生成
a = np.arange(5)
print(a)
np.put(a, [0, 2], [-44, -55])
print(a)
a = np.arange(10)
np.put(a, 22, -5, mode='clip')
print(a)
np.put(a, 23, -5, mode='wrap') # 23%10 = 3
a

[0 1 2 3 4]
[-44   1 -55   3   4]
[ 0  1  2  3  4  5  6  7  8 -5]


array([ 0,  1,  2, -5,  4,  5,  6,  7,  8, -5])

In [32]:
# put_along_axis 根据同纬度数组修改索引
# 数值索引 数组生成
a = np.array([[10, 30, 20], [60, 40, 50]])
ai = np.expand_dims(np.argmax(a, axis=1), axis=1)# 获取行中最大值索引
print("最大值索引:\n",ai)
np.put_along_axis(a, ai, 99, axis=1) #根据最大值索引替换原有数值
print("根据最大值索引，修改后的数组:\n",a)

最大值索引:
 [[1]
 [0]]
根据最大值索引，修改后的数组:
 [[10 99 20]
 [99 40 50]]


In [33]:
# putmask 用于满足条件的相应元素的计算
# 数值计算
x = np.arange(6).reshape(2, 3)
np.putmask(x, x>2, x**2)
print(x)
x = np.arange(5)
np.putmask(x, x>1, [-33, -44])
print(x)

[[ 0  1  2]
 [ 9 16 25]]
[  0   1 -33 -44 -33]


In [34]:
# pv 用于银行计算
# 同见 numpy.rate(nper, pmt, pv, fv[, when='end', guess=0.1, tol=1e-06, maxiter=100])

In [35]:
# quantile 计算中位数，比例由第二个值定，中位数为0.5
# 数值计算
a = np.array([[10, 7, 4], [3, 2, 1]])
b = a.copy()
np.quantile(b, 0.9, axis=1, overwrite_input=True)

array([9.4, 2.8])

In [36]:
# r_ 按照列连接 c_按照行连接
# 结构变化
a = np.array([[1, 2, 3],[7,8,9]])
b = np.array([[4,5,6],[1,2,3]])
g=np.r_[a,b]
print(g)

[[1 2 3]
 [7 8 9]
 [4 5 6]
 [1 2 3]]


In [37]:
# rad2deg 弧度转化为角度
# 数值计算
deg = np.arange(12.) * np.pi/4.
np.rad2deg(deg)

array([  0.,  45.,  90., 135., 180., 225., 270., 315., 360., 405., 450.,
       495.])

In [38]:
# np.radians 角度转化为弧度
# 数值计算
deg = np.arange(12.) * 30.
np.radians(deg)

array([0.        , 0.52359878, 1.04719755, 1.57079633, 2.0943951 ,
       2.61799388, 3.14159265, 3.66519143, 4.1887902 , 4.71238898,
       5.23598776, 5.75958653])

In [39]:
# random 随机方法巨多
"""
    Utility functions
    ==============================================================================
    random_sample        Uniformly distributed floats over ``[0, 1)``.
    random               Alias for `random_sample`.
    bytes                Uniformly distributed random bytes.
    random_integers      Uniformly distributed integers in a given range.
    permutation          Randomly permute a sequence / generate a random sequence.
    shuffle              Randomly permute a sequence in place.
    seed                 Seed the random number generator.
    choice               Random sample from 1-D array.
    
    ==================== =========================================================
    
    ==================== =========================================================
    Compatibility functions
    ==============================================================================
    rand                 Uniformly distributed values.
    randn                Normally distributed values.
    ranf                 Uniformly distributed floating point numbers.
    randint              Uniformly distributed integers in a given range.
"""
print(np.random.random_integers(5, size=(3,2)))
print("\n",np.random.random_integers(5, 7, size=(3,2)))
print("\n",np.random.random_integers(5, 6, 4))

[[2 2]
 [3 3]
 [5 4]]

 [[5 7]
 [7 7]
 [7 6]]

 [6 5 5 6]


/home/mathartsys/venv3/lib/python3.6/site-packages/ipykernel_launcher.py:24: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
/home/mathartsys/venv3/lib/python3.6/site-packages/ipykernel_launcher.py:25: DeprecationWarning: This function is deprecated. Please call randint(5, 7 + 1) instead
/home/mathartsys/venv3/lib/python3.6/site-packages/ipykernel_launcher.py:26: DeprecationWarning: This function is deprecated. Please call randint(5, 6 + 1) instead


In [40]:
# rank获得数据维度
# 结构识别
arr = np.array([[2,0],[3,1]])
np.rank(arr)

/home/mathartsys/venv3/lib/python3.6/site-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  This is separate from the ipykernel package so we can avoid doing imports until


2

In [41]:
# rate 用于银行计算
# 根据已有的本金，还款期，未来价值，每月还款额 计算利率
# numpy.rate(nper, pmt, pv, fv[, when='end', guess=0.1, tol=1e-06, maxiter=100])

In [42]:
# ravel 降维数组
# 结构变化
x = np.array([[1, 2, 3], [4, 5, 6]])
print(np.ravel(x))
print(np.ravel(x, order='F'))
a = np.arange(3)[::-1]; a
print(a.ravel(order='C'))
print(a.ravel(order='K'))

[1 2 3 4 5 6]
[1 4 2 5 3 6]
[2 1 0]
[2 1 0]


In [43]:
#ravel_multi_index
# 未知
arr = np.array([[2,0],[3,1]])
np.ravel_multi_index(arr, (3,4))
# （3，4）:
# [[0,1,2,3],
#  [4,5,6,7],
#  [8,9,10,11]]
# (2, 3): 3行，4列 为11

array([11,  1])

In [44]:
# real 获得复数实部,可修改实部值
# 复数计算
a = np.array([1+2j, 3+4j, 5+6j])
print(a.real)
a.real = np.array([9, 8, 7])
a

[1. 3. 5.]


array([9.+2.j, 8.+4.j, 7.+6.j])

In [45]:
# real_if_close 对虚部的操作算子
# 复数计算
print(np.real_if_close([2.1 + 4e-14j], tol=1000))
print(np.real_if_close([2.1 + 4e-13j], tol=1000))

[2.1]
[2.1+4.e-13j]


In [46]:
# rec 构造一个允许使用属性访问字段的ndarray。与recarray一致
# 结构变化
x = np.array([(1.0, 2), (3.0, 4)], dtype=[('x', float), ('y', int)])
print(x["x"]) # x.x会报错
x2 = np.rec.array(x)
x2.x

[1. 3.]


array([1., 3.])

In [47]:
# recarray 构造一个允许使用属性访问字段的ndarray。
# 结构变化
x = np.array([(1.0, 2), (3.0, 4)], dtype=[('x', float), ('y', int)])
print(x["x"]) # x.x会报错
x = x.view(np.recarray)
x.x

[1. 3.]


array([1., 3.])

In [48]:
# recfromcsv 从文件中加载ASCII数据并以记录数组的形式返回。
filename = 'data.csv'
writer = open(filename,mode='w')
writer.write('first column,second column,third column\n')
writer.write('0,1.1,1.2\n1,2.1,2.2\n2,3.1,3.2')
writer.close()

data = np.recfromcsv(filename)
print (data)

[(0, 1.1, 1.2) (1, 2.1, 2.2) (2, 3.1, 3.2)]


In [49]:
# np.recfromtxt 不知道干嘛用的
# 未知

In [50]:
# reciprocal 倒数,int和float有大区别
# 数值计算
print(np.reciprocal(1))
print(np.reciprocal(4))
print(np.reciprocal(4.))

1
0
0.25


In [51]:
# record
# 一头雾水。。这玩意有什么用？
# 未知

In [52]:
# remainder 取余 ufunc
# 数值计算
print(np.remainder([4, 7], [2, 9]))
print(np.remainder(np.arange(7), 5))

[0 7]
[0 1 2 3 4 0 1]


In [53]:
# repeat
# 数组生成
x = np.array([[1,2],[3,4],[5,6]])
print(np.repeat(x, [2, 2, 1], axis=0))
print("\n",np.repeat(x, 3, axis=1))
print("\n",np.repeat(x, 2))
print("\n",np.repeat(3, 2))

[[1 2]
 [1 2]
 [3 4]
 [3 4]
 [5 6]]

 [[1 1 1 2 2 2]
 [3 3 3 4 4 4]
 [5 5 5 6 6 6]]

 [1 1 2 2 3 3 4 4 5 5 6 6]

 [3 3]


In [54]:
# np.require 定义数据所需要的权限，妈呀。。
# 未知
x = np.arange(6).reshape(2,3)
print(x.flags)
y = np.require(x, dtype=np.float32, requirements=['A', 'O', 'W', 'F'])
print(y.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [55]:
# reshape order:C 是按照行顺序， F 是按照列顺序，A 就是按照数据在内存中存储的顺序来。
# 结构变化
a = np.arange(6).reshape((3, 2))
print(a)
print("\n",np.reshape(a, (2, 3))) # C-like index ordering
print("\n",np.reshape(a, (2, 3), order='F')) # 按照 F 顺序打散后就是 0 2 4 1 3 5， 再按照 F顺序插入， 就是结果。
print("\n",np.reshape(np.ravel(a), (2, 3), order='F'))#ravel打散 0 1 2 3 4 5,再按照 F顺序插入，就是结果。

[[0 1]
 [2 3]
 [4 5]]

 [[0 1 2]
 [3 4 5]]

 [[0 4 3]
 [2 1 5]]

 [[0 2 4]
 [1 3 5]]


In [4]:
# resize 神奇的数据重塑工具。。。。
# 数组生成
a=np.array([[0,1],[2,3]])
print(np.resize(a,(2,5)))
print("------\n",np.resize(a,(2,4)))
print("------\n",np.resize(a,(2,3)))
print("------\n",np.resize(a,(1,4)))

[[0 1 2 3 0]
 [1 2 3 0 1]]
------
 [[0 1 2 3]
 [0 1 2 3]]
------
 [[0 1 2]
 [3 0 1]]
------
 [[0 1 2 3]]


In [57]:
#np.result_type 返回数据类型
print(np.result_type('i4', 'c8'))
np.result_type(3.0, -2)

complex128


dtype('float64')

In [58]:
# right_shift 转化为二级制数，然后从右减少位数 && np.binary_repr转化为二进制数
# 数值计算
print(np.binary_repr(100)) 
print(np.right_shift(100, 4))
print(np.binary_repr(5))
print(np.right_shift(10, [1,2,3,4]))

1100100
6
101
[5 2 1 0]


In [59]:
# rint 四舍五入取整
# 数值计算
a = np.array([-1.7, -1.5, -1.4, -0.2, 0.2, 1.2, 1.7, 2.1])
print(np.rint(a))

[-2. -2. -1. -0.  0.  1.  2.  2.]


In [60]:
# roll 数据变化（滚动）！！so nice
# 数组生成
x = np.arange(16)
print(np.roll(x, 2))
x2 = np.reshape(x, (2,2,4))
print(x2)
print("\n\n无轴",np.roll(x2, 1))
print("\n\n轴0",np.roll(x2, 1, axis=0))
print("\n\n轴1",np.roll(x2, 1, axis=1))
print("\n\n轴2",np.roll(x2, 1, axis=2))

[14 15  0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


无轴 [[[15  0  1  2]
  [ 3  4  5  6]]

 [[ 7  8  9 10]
  [11 12 13 14]]]


轴0 [[[ 8  9 10 11]
  [12 13 14 15]]

 [[ 0  1  2  3]
  [ 4  5  6  7]]]


轴1 [[[ 4  5  6  7]
  [ 0  1  2  3]]

 [[12 13 14 15]
  [ 8  9 10 11]]]


轴2 [[[ 3  0  1  2]
  [ 7  4  5  6]]

 [[11  8  9 10]
  [15 12 13 14]]]


In [61]:
# rollaxis &&下文的列表示维度
# 数组生成
a = np.ones((3,4,5,6))
# print(a)
print(np.rollaxis(a, 3, 1).shape) # 第三列移到index 1前
print(np.rollaxis(a, 2).shape) # 第二列移到默认的index 0前
print(np.rollaxis(a, 1, 4).shape)# 第二列移到默认的index 4前,即3

(3, 6, 4, 5)
(5, 3, 4, 6)
(3, 5, 6, 4)


In [62]:
# root && poly 根据给定解，获得首系数为1的多项式 && poly1d 根据拟合的系数或者设定的系数，获得多项式表达式 
#&& polyfit根据已有点，获得拟合的多项式。
# 数值计算
poly= np.polyfit([10,11,12],[0,1,2],3)
p1 = np.poly1d(poly)
print(poly) #获得拟合出的多项式的系数
print(p1) #获得该多项式表达式
print(np.roots(poly)) #获得多项式=0的解

[-1.58669357e-03  5.23608879e-02  4.25616927e-01 -7.90556449e+00]
           3           2
-0.001587 x + 0.05236 x + 0.4256 x - 7.906
[ 36.60958809 -13.60958809  10.        ]


/home/mathartsys/venv3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RankWarning: Polyfit may be poorly conditioned
  This is separate from the ipykernel package so we can avoid doing imports until


In [63]:
# rot90 旋转矩阵
# 结构识别
m = np.array([[1,2],[3,4]], int)
print(np.rot90(m))
print(np.rot90(m, 2))
m = np.arange(8).reshape((2,2,2))
print("\n","\n",m)
print("\n","(1,2)","\n",np.rot90(m, 1, (1,2)))
print("\n","\n",np.rot90(m, 2, (1,2)))
print("\n","(0,1)","\n",np.rot90(m, 1, (0,1)))
print("\n","\n",np.rot90(m, 2, (0,1)))

[[2 4]
 [1 3]]
[[4 3]
 [2 1]]

 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

 (1,2) 
 [[[1 3]
  [0 2]]

 [[5 7]
  [4 6]]]

 
 [[[3 2]
  [1 0]]

 [[7 6]
  [5 4]]]

 (0,1) 
 [[[2 3]
  [6 7]]

 [[0 1]
  [4 5]]]

 
 [[[6 7]
  [4 5]]

 [[2 3]
  [0 1]]]


In [64]:
# round = round_ = around decimals保留小数的位数
# 数值计算
print(np.around([0.37, 11.64], decimals=1))
print(np.round([0.37, 111.64], decimals=-2))
print(np.round_([0.37, 11.64], decimals=-1))

[ 0.4 11.6]
[  0. 100.]
[ 0. 10.]


In [65]:
# row_stack == vstack
# 数组生成
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

In [66]:
# np.safe_eval 无用
# np.array([0, 1, 2, 3, 4])[np.s_[2::2]] 切割array
# 数组生成
np.array([0, 1, 2, 3, 4])[np.s_[2::2]]

array([2, 4])

In [67]:
# np.savez_compressed 保存压缩文件
# np.savez 保存文件含多个array
# np.save 保存文件单个array

In [68]:
"""
sctype2char
sctypeDict
sctypeNA
sctypes
"""
#与格式有关

'\nsctype2char\nsctypeDict\nsctypeNA\nsctypes\n'

In [69]:
# searchsorted 查找位置 1-D 查找后方数字按大小应在列表中的位置的索引，列表需要有序
#  数值索引
print(np.searchsorted([1,2,3,4,5], 3.5))
print(np.searchsorted([1,2,3,4,5], 3.5, side='right'))
print(np.searchsorted([1,2,3,4,5], 4))
print(np.searchsorted([1,2,3,4,5], 4, side='right'))
print(np.searchsorted([1,2,3,4,5], [-10, 10, 2, 3]))

3
3
3
4
[0 5 1 2]


In [70]:
# select 按条件计算
# 数值计算
x = np.arange(10)
condlist = [x<3, x<6, x>5]
choicelist = [x, x**2,x*2]
np.select(condlist, choicelist)

array([ 0,  1,  2,  9, 16, 25, 12, 14, 16, 18])

In [71]:
# set_string_function 不懂 set_printoptions 不懂 set_numeric_ops 太危险别玩
# 未知

In [72]:
# np.setbufsize 设置numpy数据格式占用最大缓存，np.getbufsize() 查看当前设置
print(np.getbufsize())
print(np.setbufsize(8192))

8192
8192


In [73]:
# setdiff1d a,b交集在a集下的补集 和 setxor1d a,b交集在a,b并集下的补集
# 数值计算
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 4, 5, 6])
np.setdiff1d(a, b)

array([1, 2])

In [74]:
# seterrobj 设置定义浮点错误处理的对象 seterrcall，seterr 处理数字异常用
# 未知

In [75]:
# setxor1d a,b交集在a,b并集下的补集 和 setdiff1d a,b交集在a集下的补集
# 数值计算
np.source(np.setxor1d)

In file: /home/mathartsys/venv3/lib/python3.6/site-packages/numpy/lib/arraysetops.py

def setxor1d(ar1, ar2, assume_unique=False):
    """
    Find the set exclusive-or of two arrays.

    Return the sorted, unique values that are in only one (not both) of the
    input arrays.

    Parameters
    ----------
    ar1, ar2 : array_like
        Input arrays.
    assume_unique : bool
        If True, the input arrays are both assumed to be unique, which
        can speed up the calculation.  Default is False.

    Returns
    -------
    setxor1d : ndarray
        Sorted 1D array of unique values that are in only one of the input
        arrays.

    Examples
    --------
    >>> a = np.array([1, 2, 3, 2, 4])
    >>> b = np.array([2, 3, 5, 7, 5])
    >>> np.setxor1d(a,b)
    array([1, 4, 5, 7])

    """
    if not assume_unique:
        ar1 = unique(ar1)
        ar2 = unique(ar2)

    aux = np.concatenate((ar1, ar2))
    if aux.size == 0:
        return aux

    aux.sort()
    flag = np.co

In [76]:
# shape
#  结构识别
np.shape(np.eye(3))

(3, 3)

In [77]:
# may_share_memory 查看存储位置是否一致
# 结构识别
a = np.array([1,2])
b = a
c = copy.deepcopy(a)
print(np.may_share_memory(np.array([1,2]), np.array([1,2])))
print(np.may_share_memory(a, b))
print(np.may_share_memory(a, c))

False
True
False


In [78]:
# short 转数据类型
# 数据类型
np.short(np.array([1, -2.3, 2.1]))

array([ 1, -2,  2], dtype=int16)

In [79]:
# np.show_config() 查看配置

np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [80]:
# sign 判断正负和0
# 逻辑判断
np.sign(np.array([[100, -1000.0, 0],[-34,123,11]]))

array([[ 1., -1.,  0.],
       [-1.,  1.,  1.]])

In [81]:
# signbit 判断是不是浮点数
# 逻辑判断
np.signbit(np.array([1, -2.3, 2.1]))

array([False,  True, False])

In [82]:
# signedinteger 不知道干嘛用
# 未知
np.signedinteger

numpy.signedinteger

In [83]:
# sinc ， sin 见 ufunc
# 数值计算
x = np.linspace(-4, 4, 9)
print(x)
np.sinc(x)

[-4. -3. -2. -1.  0.  1.  2.  3.  4.]


array([-3.89817183e-17,  3.89817183e-17, -3.89817183e-17,  3.89817183e-17,
        1.00000000e+00,  3.89817183e-17, -3.89817183e-17,  3.89817183e-17,
       -3.89817183e-17])

In [84]:
# single 整转浮点
# 结构变化
np.single([1,2,3])

array([1., 2., 3.], dtype=float32)

In [85]:
# singlecomplex 实转复
#  复数计算
np.singlecomplex([1+1j,2,3])

array([1.+1.j, 2.+0.j, 3.+0.j], dtype=complex64)

In [86]:
# sinh 见 tanh
# 数值计算
np.sinh((0, np.pi/8, np.pi/4))

array([0.        , 0.40287038, 0.86867096])

In [87]:
# size 类shape
# 结构识别
a = np.array([[1,2,3],[4,5,6]])
print(type(np.size(a)))
print(np.size(a))
print(np.size(a,0))
print(np.size(a,1))

<class 'int'>
6
2
3


In [88]:
# sometrue & alltrue
# 逻辑判断
print(np.sometrue(np.array([1,1,0,0])))
print(np.alltrue(np.array([1,1,0,0])))

True
False


In [89]:
# sort 实数排序

dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype)
print(np.sort(a, order='height'))
print(np.sort(a, order=['age', 'height']))

[(b'Galahad', 1.7, 38) (b'Arthur', 1.8, 41) (b'Lancelot', 1.9, 38)]
[(b'Galahad', 1.7, 38) (b'Lancelot', 1.9, 38) (b'Arthur', 1.8, 41)]


In [90]:
# np.sort_complex 对复数排序
# 复数计算
np.sort_complex([5, 3, 6, 2, 1])

array([1.+0.j, 2.+0.j, 3.+0.j, 5.+0.j, 6.+0.j])

In [91]:
# np.source 返回用python写的方法
np.source(np.interp) 

In file: /home/mathartsys/venv3/lib/python3.6/site-packages/numpy/lib/function_base.py

def interp(x, xp, fp, left=None, right=None, period=None):
    """
    One-dimensional linear interpolation.

    Returns the one-dimensional piecewise linear interpolant to a function
    with given discrete data points (`xp`, `fp`), evaluated at `x`.

    Parameters
    ----------
    x : array_like
        The x-coordinates at which to evaluate the interpolated values.

    xp : 1-D sequence of floats
        The x-coordinates of the data points, must be increasing if argument
        `period` is not specified. Otherwise, `xp` is internally sorted after
        normalizing the periodic boundaries with ``xp = xp % period``.

    fp : 1-D sequence of float or complex
        The y-coordinates of the data points, same length as `xp`.

    left : optional float or complex corresponding to fp
        Value to return for `x < xp[0]`, default is `fp[0]`.

    right : optional float or complex correspond

In [92]:
# np.spacing(2) no use

In [93]:
# split拆分
# 结构变化
"""
    array_split : Split an array into multiple sub-arrays of equal or
                  near-equal size.  Does not raise an exception if
                  an equal division cannot be made.
    hsplit : Split array into multiple sub-arrays horizontally (column-wise).
    vsplit : Split array into multiple sub-arrays vertically (row wise).
    dsplit : Split array into multiple sub-arrays along the 3rd axis (depth).
    concatenate : Join a sequence of arrays along an existing axis.
    stack : Join a sequence of arrays along a new axis.
    hstack : Stack arrays in sequence horizontally (column wise).
    vstack : Stack arrays in sequence vertically (row wise).
    dstack : Stack arrays in sequence depth wise (along third dimension)
"""
x = np.arange(8.0)
np.split(x, [3, 5, 6, 10])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

In [94]:
# sqrt 根号 见ufunc
# 数值计算
x = np.array([[[0], [1], [2]]])
print(np.sqrt(x))

[[[0.        ]
  [1.        ]
  [1.41421356]]]


In [95]:
# square 平方 见ufunc
# 数值计算
x = np.array([[[0], [1], [2]]])
print(np.square(x))

[[[0]
  [1]
  [4]]]


In [96]:
# squeeze
# 结构变化
x = np.array([[[0], [1], [2]]])
print(x.shape)
print(np.squeeze(x, axis=0).shape)
# print(np.squeeze(x, axis=1).shape)
print(np.squeeze(x, axis=2).shape)

(1, 3, 1)
(3, 1)
(1, 3)


In [97]:
# stack
# 结构变化
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.stack((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

In [98]:
# std
# (各项-均值)的平方求和后再除以N 的平方根,标准差
# 数值计算
a = np.array([[2, 4], [4, 6]])
np.std(a)

1.4142135623730951

In [99]:
# np.str,np.string_,str0,str_

In [100]:
# subtract 减法 见ufunc
# 数值计算
A = np.array([1,2,3,4,5])
B = np.array([1,2,3,4,5])
np.subtract(A,B)

array([0, 0, 0, 0, 0])

In [101]:
# sum
# 数值计算
print(np.sum([[0, 1], [0, 5]], axis=0))

print(np.sum([10], initial=5))

[0 6]
15


In [5]:
# swapaxes
# 结构变化
x = np.arange(12).reshape(4,3)
print(x)
np.swapaxes(x,1,0)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [102]:
# swapaxes 内部矩阵变换，维度交换
# 数组生成 结构变化
x = np.array([[[0,1,2,3],[20,30,40,50]],[[-4,-5,-6,-7],[-60,-70,-80,-90]],[["a","aa","aaa","aaaa"],["b","bb","bbb","bbbb"]]])
print(x,"\n", x.shape)
print("\n","\n",np.swapaxes(x,0,2),"\n", np.swapaxes(x,0,2).shape)# ==np.swapaxes(x,2,0)
print("\n","\n",np.swapaxes(x,0,1),"\n", np.swapaxes(x,0,1).shape)

[[['0' '1' '2' '3']
  ['20' '30' '40' '50']]

 [['-4' '-5' '-6' '-7']
  ['-60' '-70' '-80' '-90']]

 [['a' 'aa' 'aaa' 'aaaa']
  ['b' 'bb' 'bbb' 'bbbb']]] 
 (3, 2, 4)

 
 [[['0' '-4' 'a']
  ['20' '-60' 'b']]

 [['1' '-5' 'aa']
  ['30' '-70' 'bb']]

 [['2' '-6' 'aaa']
  ['40' '-80' 'bbb']]

 [['3' '-7' 'aaaa']
  ['50' '-90' 'bbbb']]] 
 (4, 2, 3)

 
 [[['0' '1' '2' '3']
  ['-4' '-5' '-6' '-7']
  ['a' 'aa' 'aaa' 'aaaa']]

 [['20' '30' '40' '50']
  ['-60' '-70' '-80' '-90']
  ['b' 'bb' 'bbb' 'bbbb']]] 
 (2, 3, 4)


In [103]:
# np.sys 系统sys方法调用
np.sys.version

'3.6.3 (default, May 14 2018, 15:21:42) \n[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]'

In [104]:
# take 按给定索引生成数组
# 数组生成
a = [4, 3, 5, 7, 6, 8]
np.take(a, [[0, 1], [2, 3]])

array([[4, 3],
       [5, 7]])

In [105]:
# take_along_axis 按照给定数组映射的索引重排序
# 数组生成
a = np.array([[10, 30], [60, 40]])
ai = np.argsort(a, axis=1)
print(np.take_along_axis(a, ai, axis=0))
print(np.take_along_axis(a, ai, axis=1))

[[10 40]
 [60 30]]
[[10 30]
 [40 60]]


In [106]:
# tan 见ufunc
# 数值计算
np.tan((0, np.pi/8, np.pi/4))

array([0.        , 0.41421356, 1.        ])

In [107]:
# np.sinh(x)/np.cosh(x) or -1j * np.tan(1j*x)
# 数值计算
np.tanh((0, np.pi/8, np.pi/4))

array([0.        , 0.37368475, 0.6557942 ])

In [108]:
# tensordot 
# 实现多维数组求平均的动作（每一个二维平面对应位的平均）
# 数值计算
X = np.random.randint(0, 5, [3, 2, 2])
print(X)
print("==================/n",np.tensordot(X, [1/3, 1/3, 1/3], axes=([0], [0])))
# 多维数组
a = np.array(range(1, 9))
a.shape = (2, 2, 2)
print(a.shape)
A = np.array(('a', 'b', 'c', 'd'), dtype=object)
A.shape = (2, 2)
print(A.shape)
print(np.tensordot(a, A, (2, 1)))

[[[1 2]
  [3 0]]

 [[2 0]
  [3 0]]

 [[1 0]
  [3 2]]]
[[1.33333333 0.66666667]
 [3.         0.66666667]]
(2, 2, 2)
(2, 2)
[[['abb' 'cdd']
  ['aaabbbb' 'cccdddd']]

 [['aaaaabbbbbb' 'cccccdddddd']
  ['aaaaaaabbbbbbbb' 'cccccccdddddddd']]]


In [109]:
# numpy.testing包中有很多实用的工具函数考虑了浮点数比较的问题，可以测试前提是否成立。include test
print ("Pass", np.testing.assert_string_equal("NumPy", "NumPy"))
"""
assert_almost_equal 如果两个数字的近似程度没有达到指定精度，就抛出异常
assert_approx_equal 如果两个数字的近似程度没有达到指定有效数字，就抛出异常
assert_array_almost_equal 如果两个数组中元素的近似程度没有达到指定精度，就抛出异常
assert_array_equal 如果两个数组对象不相同，就抛出异常
assert_array_less 两个数组必须形状一致，并且第一个数组的元素严格小于第二个数组的元素，否则就抛出异常
assert_equal 如果两个对象不相同，就抛出异常
assert_raises 若用填写的参数调用函数没有抛出指定的异常，则测试不通过
assert_warns 若没有抛出指定的警告，则测试不通过
assert_string_equal 断言两个字符串变量完全相同
assert_allclose 如果两个对象的近似程度超出了指定的容差限，就抛出异常

https://blog.csdn.net/m0_37264397/article/details/79010234
"""

Pass None


'\nassert_almost_equal 如果两个数字的近似程度没有达到指定精度，就抛出异常\nassert_approx_equal 如果两个数字的近似程度没有达到指定有效数字，就抛出异常\nassert_array_almost_equal 如果两个数组中元素的近似程度没有达到指定精度，就抛出异常\nassert_array_equal 如果两个数组对象不相同，就抛出异常\nassert_array_less 两个数组必须形状一致，并且第一个数组的元素严格小于第二个数组的元素，否则就抛出异常\nassert_equal 如果两个对象不相同，就抛出异常\nassert_raises 若用填写的参数调用函数没有抛出指定的异常，则测试不通过\nassert_warns 若没有抛出指定的警告，则测试不通过\nassert_string_equal 断言两个字符串变量完全相同\nassert_allclose 如果两个对象的近似程度超出了指定的容差限，就抛出异常\n\nhttps://blog.csdn.net/m0_37264397/article/details/79010234\n'

In [110]:
# tile 数组广播
# 数值生成
a = np.array([0, 1, 2])
print(np.tile(a, 2))

print(np.tile(a, (2, 2)))

print(np.tile(a, (2, 1, 2)))

[0 1 2 0 1 2]
[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]
[[[0 1 2 0 1 2]]

 [[0 1 2 0 1 2]]]


In [111]:
# timedelta64 输入时间

np.datetime64('2005-02-25')

numpy.datetime64('2005-02-25')

In [112]:
# trace
# 数值计算
print("求迹",np.trace(np.eye(3)))
np.trace(np.arange(24).reshape((2,2,2,3))).shape

求迹 3.0


(2, 3)

In [113]:
# np.tracemalloc_domain
# 未知
np.tracemalloc_domain # 内存分配？

389047

In [114]:
# transpose 转秩
# 结构变化
x = np.arange(4).reshape((2,2))
print(x)
print(np.transpose(x))

x = np.ones((1, 2, 3))
print(x.shape)
np.transpose(x, (1, 0, 2)).shape # 1和2的维度对调

[[0 1]
 [2 3]]
[[0 2]
 [1 3]]
(1, 2, 3)


(2, 1, 3)

In [115]:
# np.trapz
# 数值计算
print("ex.1",np.trapz([1,6]))## 直角梯形的积分！(1+6)*(6-1)/2
print("ex.2",np.trapz([1,3], x=[4,8]))## 直角梯形的积分！(1+3)*(8-4)/2
print("ex.3",np.trapz([1,3], dx=4))## 直角梯形的积分！(1+3)*4/2
a = np.arange(6).reshape(2, 3)
print(a)
print("ex.4",np.trapz(a, axis=0))## 直角梯形的积分！[(0+3)*(3-0)/2,(1+4)*(4-1)/2,(2+5)*(5-2)/2]
print("ex.5",np.trapz(a, axis=1))## 直角梯形的积分！[(0+1)*(1-0)/2+(1+2)*(2-1)/2,(3+4)*(4-3)/2+(4+5)*(5-4)/2]

ex.1 3.5
ex.2 8.0
ex.3 8.0
[[0 1 2]
 [3 4 5]]
ex.4 [1.5 2.5 3.5]
ex.5 [2. 8.]


In [6]:
# tri
# 下三角矩阵填写
# 数组生成
print(np.tri(3, 5, -1))
print("-----------\n",np.tri(3, 5, 2))

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]]
-----------
 [[1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


In [117]:
# tril,tril_indices 与 triu,triu_indices

In [118]:
# np.tril_indices_from
# 数值索引
a = np.array([[1, 2, 3, 4],[1, 2, 3, 4]])
print("k=2",np.tril_indices_from(a,k=2))
ui1 = np.tril_indices_from(a,k=2)
a[ui1] = -1
print(a)
a = np.array([[1, 2, 3, 4],[1, 2, 3, 4]])
print("k=0",np.tril_indices_from(a,k=0))
ui2 = np.tril_indices_from(a,k=0)
a[ui2] = -1
print(a)

k=2 (array([0, 0, 0, 1, 1, 1, 1]), array([0, 1, 2, 0, 1, 2, 3]))
[[-1 -1 -1  4]
 [-1 -1 -1 -1]]
k=0 (array([0, 1, 1]), array([0, 0, 1]))
[[-1  2  3  4]
 [-1 -1  3  4]]


In [119]:
# 只能对一位数组去0，默认为fb即两头去0，f为front，b为back
# 数组生成
a = np.array([0, 0, 0, 1, 2, 3, 0, 2, 1, 0])
print("raw",a)
print("fb",np.trim_zeros(a))
print("f",np.trim_zeros(a,"f"))
print("b",np.trim_zeros(a,"b"))

raw [0 0 0 1 2 3 0 2 1 0]
fb [1 2 3 0 2 1]
f [1 2 3 0 2 1 0]
b [0 0 0 1 2 3 0 2 1]


In [120]:
print("4",np.triu(np.arange(24).reshape(4, 6), 4))
print("0",np.triu(np.arange(24).reshape(4, 6), 0))
print("-2",np.triu(np.arange(24).reshape(4, 6), -2))

4 [[ 0  0  0  0  4  5]
 [ 0  0  0  0  0 11]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]
0 [[ 0  1  2  3  4  5]
 [ 0  7  8  9 10 11]
 [ 0  0 14 15 16 17]
 [ 0  0  0 21 22 23]]
-2 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [ 0 19 20 21 22 23]]


In [121]:
# 数组生成
iu1 = np.triu_indices(4)
#(array([0, 0, 0, 0, 1, 1, 1, 2, 2, 3]), array([0, 1, 2, 3, 1, 2, 3, 2, 3, 3])) 第一个组array代表所在行，第二组array映射为所在行的所在列
# [1,1,1,1]
# [0,1,1,1]
# [0,0,1,1]
# [0,0,0,1]
iu2 = np.triu_indices(4, 1)
# 从左往右各行减1
#(array([0, 0, 0, 1, 1, 2]), array([1, 2, 3, 2, 3, 3]))
# [0,1,1,1]
# [0,0,1,1]
# [0,0,0,1]
# [0,0,0,0]
iu3 = np.triu_indices(4, 1, 3)
# 从右往左各行减4-3
#(array([0, 0, 0, 1, 1, 2]), array([1, 2, 3, 2, 3, 3]))
# [0,1,1,0]
# [0,0,1,0]
# [0,0,0,0]
# [0,0,0,0]
a = np.arange(25).reshape(5, 5)
print("a[iu1]",a[iu1])
a[iu1] = -1
print(a)
a = np.arange(25).reshape(5, 5)
print("a[iu2]",a[iu2])
a[iu2] = -1
print(a)
a = np.arange(25).reshape(5, 5)
print("a[iu3]",a[iu3])
a[iu3] = -1
print(a)

a[iu1] [ 0  1  2  3  6  7  8 12 13 18]
[[-1 -1 -1 -1  4]
 [ 5 -1 -1 -1  9]
 [10 11 -1 -1 14]
 [15 16 17 -1 19]
 [20 21 22 23 24]]
a[iu2] [ 1  2  3  7  8 13]
[[ 0 -1 -1 -1  4]
 [ 5  6 -1 -1  9]
 [10 11 12 -1 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
a[iu3] [1 2 7]
[[ 0 -1 -1  3  4]
 [ 5  6 -1  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [8]:
a = np.array([[1, 2, 3, 4],[1, 2, 3, 4]])
# [1,(2, 3, 4)]
# [1, 2,(3, 4)]
iu1 = np.triu_indices_from(a,k=2)# k==1代表从index=1开始取
print("k=2",iu1)
print("-----------------\n",a[iu1])
a[iu1] = -1
print("-----------------\n",a)

iu1 = np.triu_indices_from(a,k=0)# k==1代表从index=1开始取
print("---------k=0--------\n",iu1)
print("-----------------\n",a[iu1])
a[iu1] = -1
print("-----------------\n",a)

k=2 (array([0, 0, 1]), array([2, 3, 3]))
-----------------
 [3 4 4]
-----------------
 [[ 1  2 -1 -1]
 [ 1  2  3 -1]]
---------k=0--------
 (array([0, 0, 0, 0, 1, 1, 1]), array([0, 1, 2, 3, 1, 2, 3]))
-----------------
 [ 1  2 -1 -1  2  3 -1]
-----------------
 [[-1 -1 -1 -1]
 [ 1 -1 -1 -1]]


In [123]:
#trunc==ufunc==true_divide
# 数值计算

In [124]:
#np.typeNA,np.typeDict，
## 数据类型对应的XX码？？？
# 未知
np.typecodes

{'Character': 'c',
 'Integer': 'bhilqp',
 'UnsignedInteger': 'BHILQP',
 'Float': 'efdg',
 'Complex': 'FDG',
 'AllInteger': 'bBhHiIlLqQpP',
 'AllFloat': 'efdgFDG',
 'Datetime': 'Mm',
 'All': '?bhilqpBHILQPefdgFDGSUVOMm'}

In [125]:
# 获得numpy数据类型缩写的具体数据类型描述
np.typename("q")

'long long integer'

### np.ufunc 矩阵计算，可以自己定义，但内置计算方法是基于C封装的，速度最快

In [126]:
a1=np.add.reduce([1,2,3])                  #1+2+3=6
print(a1)
a2=np.add.reduce([[1,2,3],[4,5,6]])        #[1+4,2+5,3+6]=[5,7,9]
print(a2)
a3=np.add.reduce([[1,2,3],[4,5,6]],axis=1) #[1+2+3,4+5+6]=[6,15]
print(a3)
a4=np.add.reduce([[1,2,3],[4,5,6]],axis=0) #[14,2+5,3+6]=[5,7,9]
print(a4)

"""
reduce和accumulate可以对双参函数进行运算

其它双参运算函数：
a + b    add(a,b)
a - b    subtract(a,b)
a * b    multiply(a,b)
a / b    divide(a,b)
a ** b   power(a,b) 幂运算
a % b    remainder(a,b) 取余
"""

6
[5 7 9]
[ 6 15]
[5 7 9]


'\nreduce和accumulate可以对双参函数进行运算\n\n其它双参运算函数：\na + b    add(a,b)\na - b    subtract(a,b)\na * b    multiply(a,b)\na / b    divide(a,b)\na ** b   power(a,b) 幂运算\na % b    remainder(a,b) 取余\n'

In [127]:
## at
# 数值计算
a = np.array([1, 2, 3, 4])
np.negative.at(a, [0, 1])
print("1.单参数运算",a)

a = np.array([1, 2, 3, 4])
np.add.at(a, [0, 1, 2, 2], 1)# 对a中索引为[0, 1, 2, 2]中的数值加上1.
print("2.双参数运算",a)

a = np.array([1, 2, 3, 4])
b = np.array([1, 2])
np.add.at(a, [0, 1], b)
print("3.双参数运算",a)# 对a中索引为[0, 1]中的数值,对应加上[1, 2].

1.单参数运算 [-1 -2  3  4]
2.双参数运算 [2 3 5 4]
3.双参数运算 [2 4 3 4]


In [25]:
## reduceat
# 数值计算
B = np.arange(9)
B3 = np.add.reduceat(B,[0,5,2,7])
print (B3)
# [10 5 20 15]
# 解析：第一步用到索引值列表中的0和5，实际上就是对数组中索引值在0到5之间的元素进行reduce操作。
print (np.add.reduce(B[0:5]))
# 第二步用到索引值5和2。由于2比5小，所以直接返回索引值为5的元素
print (np.add.reduce(B[5]))
# 第三步用到索引值2和7。这一步是对索引值在2到7之间的数组元素进行reduce操作
print (np.add.reduce(B[2:7]))
# 第四步用到索引值7。这一步是对索引值从7开始直到数组末端的元素进行reduce操作
print (np.add.reduce(B[7:]))

x = np.linspace(0, 15, 16).reshape(4,4)
print("raw_data",x)
print("example_2",np.add.reduceat(x, [0, 3, 1, 2, 0]))
print("example_3,axis=0",np.multiply.reduceat(x, [0, 3], axis=0))
print("example_3,axis=1",np.multiply.reduceat(x, [0, 3], axis=1))

[10  5 20 15]
10
5
20
15
raw_data [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
example_2 [[12. 15. 18. 21.]
 [12. 13. 14. 15.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [24. 28. 32. 36.]]
example_3,axis=0 [[  0.  45. 120. 231.]
 [ 12.  13.  14.  15.]]
example_3,axis=1 [[   0.    3.]
 [ 120.    7.]
 [ 720.   11.]
 [2184.   15.]]


In [129]:
## accumulate
# 数值计算
b1=np.add.accumulate([1,2,3])                          #[1,1+2,1+2+3]=[1,3,6]
print(b1)
b2=np.add.accumulate([[1,2,3],[4,5,6],[7,8,9]],axis=0) #
print(b2)
b3=np.add.accumulate([[1,2,3],[4,5,6],[7,8,9]],axis=1) 
print(b3)

[1 3 6]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


In [10]:
## outer
# 数值计算
print(np.multiply([1, 2, 3], [4, 5, 6]))
print("--------outer--------\n",np.multiply.outer([1, 2, 3], [4, 5, 6]))

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2, 3, 4]])
C = np.multiply.outer(A, B)
print("----------------\n",C.shape,"\n----------------\n",C)

[ 4 10 18]
--------outer--------
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
----------------
 (2, 3, 1, 4) 
----------------
 [[[[ 1  2  3  4]]

  [[ 2  4  6  8]]

  [[ 3  6  9 12]]]


 [[[ 4  8 12 16]]

  [[ 5 10 15 20]]

  [[ 6 12 18 24]]]]


In [131]:
## identity,nargs,nin,nout,ntypes,signature,types
## np.add.nin 输入的参数
## np.add.nout 输出的参数
## np.add.signature 输入输出的矩阵维度变化

In [132]:
A = np.array([1,2,3,4,5])
B = np.array([1,2,3,4,5])
print('A+B = ',np.add(A,B))
print('A*B = ',np.multiply(A,B))

A+B =  [ 2  4  6  8 10]
A*B =  [ 1  4  9 16 25]


In [133]:
A = np.array([1,2,3,4,5])
B = np.array([1,2,3,4,5])
np.subtract(A,B)

array([0, 0, 0, 0, 0])

#### 以上为ufunc

In [134]:
np.ubyte
np.uint
np.uint0
np.uint16
np.uint32
np.uint64
np.uint8
np.uintc
np.uint
np.ulonglong
np.unicode#数据格式
np.unicode_

numpy.str_

In [11]:
# union1d
# 数组生成
from functools import reduce

print(np.union1d([-1, 0, 1], [-2, 0, 2]))
print("----------------\n",reduce(np.union1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2])))

[-2 -1  0  1  2]
----------------
 [1 2 3 4 6]


In [136]:
# unique
# 数组生成
print(np.unique([1, 1, 2, 2, 3, 3]))
a = np.array([[1, 1], [2, 3]])
print(np.unique(a))
a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
print("axis=0",np.unique(a, axis=0))
a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
print("axis=1",np.unique(a, axis=1))

a = np.array(['a', 'b', 'b', 'c', 'a'])
u,indices = np.unique(a, return_index=True)
print("u,indices",u,indices)
print(a[indices])

a = np.array([1, 2, 6, 4, 2, 3, 2])
u, indices = np.unique(a, return_inverse=True)
print("u",u)
u[indices]

[1 2 3]
[1 2 3]
axis=0 [[1 0 0]
 [2 3 4]]
axis=1 [[0 0 1]
 [0 0 1]
 [3 4 2]]
u,indices ['a' 'b' 'c'] [0 1 3]
['a' 'b' 'c']
u [1 2 3 4 6]


array([1, 2, 6, 4, 2, 3, 2])

In [137]:
# unpackbits 相当有意思，数值转化为二进制
a = np.array([[2], [7], [23]], dtype=np.uint8)
print(a)
b = np.unpackbits(a, axis=1)
b #转化为二进制

[[ 2]
 [ 7]
 [23]]


array([[0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 0, 1, 1, 1]], dtype=uint8)

In [138]:
np.unravel_index(indices=[22, 41, 37], dims=(7,6))
# 首先构造一个数组arr1=np.array(range(7*6)).reshape((7,6));返回indices中的元素值在数组arr1中对应值的索引位置。
# [3,6, 6]分别对应[22, 41, 37]在第1维中的位置，[4,5, 1]分别对应[22,41, 37]在2维中的位置。

(array([3, 6, 6]), array([4, 5, 1]))

In [139]:
np.unsignedinteger#无符号，双精度整数

numpy.unsignedinteger

In [140]:
# unwrap 傅里叶变换有关（2pi）
# 数值计算
phase = np.array([2.67, -0.92, -1.37, -0.58, 0, 0,78, -2.94])
np.unwrap(phase)

array([2.67      , 5.36318531, 4.91318531, 5.70318531, 6.28318531,
       6.28318531, 8.88496162, 9.62637061])

In [141]:
np.ushort#短整型

numpy.uint16

In [12]:
# vander 数组生成

x = np.array([1, 2, 3, 5])
N = 3#默认为4
print(np.vander(x))
print("----------------\n",np.vander(x,N))
print("----------------\n",np.vander(x, N, increasing=True))

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
----------------
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
----------------
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]]


In [143]:
## var = mean(abs(x - x.mean())**2)
# 数值计算
X = np.array([[1, 2], [3, 4], [5, 6]])
print (np.var(X, axis=0, keepdims=True))
print (np.var(X, axis=1, keepdims=True))
print (np.var(X))

[[2.66666667 2.66666667]]
[[0.25]
 [0.25]
 [0.25]]
2.9166666666666665


In [144]:
# vdot
# 数值计算
a = np.array([1+2j,3+4j])
b = np.array([5+6j,7+8j])
print("1",np.vdot(a,b))
print("2",np.vdot(b,a))

a = np.array([[1, 4], [5, 6]])
b = np.array([[4, 1], [2, 2]])
# 1*4 + 4*1 + 5*2 + 6*2
print("1",np.vdot(a,b))
print("2",np.vdot(b,a))

1 (70-8j)
2 (70+8j)
1 30
2 30


### np.vectorize

In [145]:
def myfunc(a, b):
    if a > b:
        return a - b
    else:
        return a + b

vfunc = np.vectorize(myfunc)

print(vfunc([1, 2, 3, 4], 2))


def mypolyval(p, x):
    _p = list(p)
    res = _p.pop(0)
    while _p:
        res = res*x + _p.pop(0)
    return res
vpolyval = np.vectorize(mypolyval, excluded=['p'])#用excluded可以用来防止对某些参数矢量化
print(vpolyval(p=[1, 2, 3], x=[0, 1]))

[3 4 1 2]
[3 6]


In [146]:
np.version

<module 'numpy.version' from '/home/mathartsys/venv3/lib/python3.6/site-packages/numpy/version.py'>

In [147]:
# void
# 未知
dt = np.dtype([('name', np.str_, 16), ('grades', np.float64, (2,))])
x = np.array([('Sarah', (8.0, 7.0)), ('John', (6.0, 7.0))], dtype=dt)
print(type(x))
print(type(x[1]))
print(x[1])
print(x[1]["name"])
x2 = np.void0(10)
print(x2)
x3 = np.void(10)
print(x3.shape)

<class 'numpy.ndarray'>
<class 'numpy.void'>
('John', [6., 7.])
John
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
()


In [148]:
#'all', 'any', 'argmax', 'argmin', 'argsort', 'astype', 'base', 'byteswap', 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'cumprod', 'cumsum', 'data', 'diagonal', 'dtype', 'dump', 'dumps', 'fill', 'flags', 'flat', 'flatten', 'getfield', 'imag', 'item', 'itemset', 'itemsize', 'max', 'mean', 'min', 'nbytes', 'ndim', 'newbyteorder', 'nonzero', 'prod', 'ptp', 'put', 'ravel', 'real', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 'setfield', 'setflags', 'shape', 'size', 'sort', 'squeeze', 'std', 'strides', 'sum', 'swapaxes', 'take', 'tobytes', 'tofile', 'tolist', 'tostring', 'trace', 'transpose', 'var', 'view', 'argpartition', 'ctypes', 'dot', 'partition'
#'all', 'any', 'argmax', 'argmin', 'argsort', 'astype', 'base', 'byteswap', 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'cumprod', 'cumsum', 'data', 'diagonal', 'dtype', 'dump', 'dumps', 'fill', 'flags', 'flat', 'flatten', 'getfield', 'imag', 'item', 'itemset', 'itemsize', 'max', 'mean', 'min', 'nbytes', 'ndim', 'newbyteorder', 'nonzero', 'prod', 'ptp', 'put', 'ravel', 'real', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 'setfield', 'setflags', 'shape', 'size', 'sort', 'squeeze', 'std', 'strides', 'sum', 'swapaxes', 'take', 'tobytes', 'tofile', 'tolist', 'tostring', 'trace', 'transpose', 'var', 'view'

In [149]:
# vsplit
# 结构变化
x = np.arange(16.0).reshape(4, 4)
print(x)
print(np.vsplit(x, np.array([1,3])))# 先切至row==1，再切至row==3,剩下的自成一派。没有则为空。
print(np.split(x, [1,3], axis=0))
print(np.vsplit(x, 2))
print(np.split(x, 2, axis=0))

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
[array([[0., 1., 2., 3.]]), array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]]), array([[12., 13., 14., 15.]])]
[array([[0., 1., 2., 3.]]), array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]]), array([[12., 13., 14., 15.]])]
[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]
[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]


In [150]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(np.vstack((a,b)))
print(np.stack((a,b),axis = 0))

[[1 2 3]
 [2 3 4]]
[[1 2 3]
 [2 3 4]]


In [151]:
# warnings
# 未知
np.warnings# 跳过

<module 'warnings' from '/home/mathartsys/venv3/lib/python3.6/warnings.py'>

In [152]:
# [[True,False], [True,False]]，分别对应最后输出结果的四个值。第一个值从[1,9]中选，因为条件为True，所以是选1
# 第二个值从[2,8]中选，因为条件为False，所以选8，后面以此类推。
print(np.where([[True, False], [True, True]],
         [[1, 2], [3, 4]],
         [[9, 8], [7, 6]]))

# [[1, 2], [1, 0]]，值大于0的位置，(array([0, 0, 1]), array([0, 1, 0]))
# 两个array对应[0,0],[0,1],[1,0]
print(np.where([[1, 2], [1, 0]]))

[[1 8]
 [3 4]]
(array([0, 0, 1]), array([0, 1, 0]))


In [153]:
a = np.arange(10)
b = np.ones(20)
np.who()# 所有在kernal里的numpy数据。

Name            Shape               Bytes            Type

a               10                  80               int64
b               20                  160              float64
_2              2 x 2 x 1           4                uint8
m               2 x 2 x 2           64               int64
y               2 x 3               24               float32
arr             2 x 2               32               int64
_9              2 x 3               48               int64
x               4 x 4               128              float64
z               4                   32               float64
_19             5                   40               int64
_21             3                   24               int64
_23             3                   24               int64
_31             10                  80               int64
ai              2 x 2               32               int64
_35             2                   16               float64
g               4 x 3               96        

In [154]:
# zeros_like
# 数组生成
x = np.arange(6)
x = x.reshape((2, 3))

np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])